### ISSUE TITLE
display still doesnt work

### ISSUE THREAD

**Issue by qNnOtTk** [mrkprdo/radxa-zero-spi-display#1]
running this command make && sudo cp {fb_st7735r.ko,fbtft.ko} /usr/lib/modules/5.10.69-10-amlogic-g615a45dd0fce/kernel/drivers/staging/fbtft/ (my display is a st7735r) gives make error how do i fix this

this is whats in that folder:
`fb_hx8353d.ko  fb_ili9486.ko  fb_ssd1305.ko  fb_tls8204.ko
fb_hx8357d.ko  fb_pcd8544.ko  fb_ssd1306.ko  fb_uc1611.ko
fb_ili9163.ko  fb_ra8875.ko   fb_ssd1325.ko  fb_uc1701.ko
fb_ili9320.ko  fb_s6d02a1.ko  fb_ssd1331.ko  fb_upd161704.ko
fb_agm1264k-fl.ko  fb_ili9325.ko  fb_s6d1121.ko  fb_ssd1351.ko  fb_watterott.ko
fb_bd663474.ko     fb_ili9340.ko  fb_seps525.ko  fb_st7735r.ko  fbtft.ko
fb_hx8340bn.ko     fb_ili9341.ko  fb_sh1106.ko   fb_st7789v.ko
fb_hx8347d.ko      fb_ili9481.ko  fb_ssd1289.ko  fb_tinylcd.ko
`

**Comment by mrkprdo** [comment]
Hi, were you able to pull the whole repo?
if you check the folder it does have the Makefile
you need to run the command inside the `kernel-linux-5.10.y-radxa-zero/drivers/staging/fbtft/`

**Comment by qNnOtTk** [comment]
Yes, i did that, this issue is solved but now I have another one.
Every step i followed in the readme file worked perfectly fine, 0 errors but the display still showed up nothing.
This is my dtbo file I used:
directory and filename: /boot/dtbs/5.10.69-10-amlogic-g617a45dd0fce/amlogic/overlay/meson-g12a-spi-lcd.dtbo
```
/dts-v1/;
/plugin/;

/ {
        compatible = "radxa,zero", "amlogic,g12a";

        fragment@0 {
                target = <&spicc1>;
                __overlay__ {
                        #address-cells = <1>;
                        #size-cells = <0>;
                        pinctrl-0 = <&spicc1_pins &spicc1_ss0_pins>;
                        pinctrl-names = "default";
                        st7789v@0 {
                        compatible = "sitronix,st7735r";
                        status = "okay";
                        reg = <0>;
                        spi-max-frequency = <10000000>;
                        width = <128>;
                        height = <128>;
                        buswidth = <8>;
                        fps = <50>;
                        rotate = <270>;
                        debug = <7>;


                        reset-gpios = <0x2b 73 1>;
                        dc-gpios = <0x2b 75 0>;
                        led-gpios = <0x2b 74 0>;
                        };
                };
        };
};
```


My uEnv.txt file:
```
verbosity=7
rootfstype=ext4
overlay_prefix=meson

overlays=meson-g12a-i2c-ao-m0-gpioao-2-gpioao-3 meson-g12a-i2c-ee-m1-gpioh-6-gpioh-7 meson-g12a-i2c-ee-m3-gpioa-14-gpioa-15 meson-g12a-spi-spidev meson-g12a-spi-lcd
param_spidev_spi_bus=0
param_spidev_max_freq=10000000
```


also, i mean nothing as in the screen never blinked or actually did anything, it just stayed white for the entire time
if you're wondering checking dmesg, dmesg | grep fbtft shows nothing
i also tried looking up in dmesg anything related to dtoverlays, still shows nothing, which only leads me to suspecting that i did something wrong in uEnv.txt

**Comment by qNnOtTk** [comment]
nevermind i reinstalled debian followed the tutorial carefully and it works now
